### PR TITLE
Specify dart 2.0

### PR DESCRIPTION
**Pull request by andreidiaconu**
Without this I get `Because x depends on flutter_amplitude >=0.0.2 which requires SDK version <2.0.0, version solving failed.` whenever I try to do `flutter upgrade`. I think that if not specified, dart below 2.0 is assumed by default.

The code is actually the same as most of the official flutter plugins.

### CODE REVIEW

**Comment by andreidiaconu** [comment]
@MiguelCatalan Hi! Did you get a chance to look at this?

**Comment by MiguelCatalan** [comment]
Sorry I didn't saw this thread.

I was planning to do this. Thanks for the PR, I will take a look at it asap.

**Comment by arok** [comment]
Up!

**Comment by andreidiaconu** [comment]
@arok 
> Up!

If you're blocked by this you have the option to include the library using git directly, in your `pubspec.yaml`:
```
  flutter_amplitude:
    git:
      url: git://github.com/andreidiaconu/flutter_amplitude.git
      ref: patch-1
```
This is what I did. Hope it helps. Cheers ✌️

**Comment by MiguelCatalan** [comment]
Sorry I was unable to maintain this until now. Sorry for the delay, already updated at `v0.1.1`!

**Pull request merged**
